[versions]
kotlin = "1.7.20"
compose = "1.2.2"

jna = "5.11.0"

dokka = "1.7.0"
vanniktech-publish = "0.20.0"


[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }

dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
vanniktech-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-publish" }

[libraries]
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }